resources: !include lovelace/global_cards/resources.yaml
popup_cards: !include lovelace/global_cards/pop_up_cards.yaml
button_card_templates: !include lovelace/global_cards/button_card_templates.yaml
title: Home Control
custom_header:
  header_text: 'Home Control'
  button_text:
    options: '{{ time }}'
  hide_unused: true
  voice_hide: true
  default_tab_on_refresh: false
  hide_config: true
  hide_raw: true
  hide_help: true
  background: '#3b4049'
  active_tab_color: rgb(19, 172, 198)
  compact_mode: true
  indicator_top: true
  default_tab: home
  exceptions:
    - conditions:
        query_string: kiosk
      config:
        kiosk_mode: true
views:
  - !include lovelace/00_main_view.yaml
  - !include lovelace/01_media_player_view.yaml
  - !include lovelace/02_calendar_view.yaml
  - !include lovelace/03_system_view.yaml