homeassistant:
  name: Atlanta Condo
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 363
  unit_system: imperial
  time_zone: America/New_York
  customize: !include yamls/home_assistant_yamls/customize.yaml
  whitelist_external_dirs:
    - /config/
    - /
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - !secret trusted_network
        - 172.30.32.0/24
    - type: legacy_api_password
      api_password: !secret http_password
frontend: !include yamls/home_assistant_yamls/frontend.yaml

custom_updater:

config:

hassio:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  cors_allowed_origins: !include yamls/home_assistant_yamls/cors_allowed_origins.yaml

api:

logger:
  default: error
  logs:
    homeassistant.components.system_log: fatal
    homeassistant.components.tplink: fatal

lovelace:
  mode: yaml

system_health:

discovery:
  ignore:
    - roku
    - google_cast

sun: !include yamls/home_assistant_yamls/sun.yaml

tts: !include yamls/home_assistant_yamls/tts.yaml

vera:
  vera_controller_url: !secret vera_controller_url
  exclude: [58]

wemo:
  discovery: false
  static:
    - !secret yi_cam_outlet

google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

ifttt:
  key: !secret ifttt_key

updater:
  include_used_components: true
weather:
  - platform: darksky
    mode: daily
    api_key: !secret darksky_api_key

speedtestdotnet:
  scan_interval:
    minutes: 15

# Include Folders
automation: !include_dir_merge_list yamls/automation
script: !include_dir_merge_named yamls/scripts
sensor: !include_dir_merge_list yamls/sensors

# Include HA Yamls
input_number: !include yamls/home_assistant_yamls/input_numbers.yaml
input_select: !include yamls/home_assistant_yamls/input_select.yaml
notify: !include yamls/home_assistant_yamls/notify.yaml
binary_sensor: !include yamls/home_assistant_yamls/binary_sensors.yaml
recorder: !include yamls/home_assistant_yamls/recorder.yaml
input_boolean: !include yamls/home_assistant_yamls/input_boolean.yaml
logbook: !include yamls/home_assistant_yamls/logbook.yaml
history: !include yamls/home_assistant_yamls/history.yaml
input_text: !include yamls/home_assistant_yamls/input_text.yaml
# panel_iframe: !include yamls/home_assistant_yamls/panel_iframe.yaml
panel_custom: !include yamls/home_assistant_yamls/panel_custom.yaml
rest_command: !include yamls/home_assistant_yamls/rest_command.yaml
shell_command: !include yamls/home_assistant_yamls/shell_commands.yaml
scene: !include yamls/home_assistant_yamls/scenes.yaml
group: !include yamls/home_assistant_yamls/groups.yaml
weblink: !include yamls/home_assistant_yamls/weblink.yaml
influxdb: !include yamls/home_assistant_yamls/influxdb.yaml

# Include Devices Yamls
device_tracker: !include yamls/devices/device_tracker.yaml
switch: !include yamls/devices/switches.yaml
media_player: !include yamls/devices/media_player.yaml
light: !include yamls/devices/lights.yaml
climate: !include yamls/devices/climate.yaml
mqtt: !include yamls/devices/mqtt.yaml
cast: !include yamls/devices/cast.yaml
hdmi_cec: !include yamls/devices/cec.yaml
googlehome: !include yamls/devices/googlehome.yaml
tplink: !include yamls/devices/tplink.yaml
tuya: !include yamls/devices/tuya.yaml
folder_watcher: !include yamls/devices/folder_watcher.yaml
zone: !include yamls/devices/zone.yaml
google_assistant: !include yamls/devices/google_assistant.yaml
joaoapps_join: !include yamls/devices/join.yaml
proximity: !include yamls/devices/proximity.yaml