homeassistant:
  name: Home Control
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 363
  unit_system: imperial
  time_zone: America/New_York
  customize: !include yamls/front_end/customize.yaml
  external_url: !secret base_url
  internal_url: !secret hass_http_ip
  allowlist_external_dirs:
    - /config/
    - /
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - !secret trusted_home_network
      trusted_users:
        192.168.1.0/24:
          - !secret trusted_user_neil
          - !secret trusted_user_phone
      allow_bypass_login: true
frontend: !include yamls/front_end/frontend.yaml

sun:
api:
config:
websocket_api:
system_health:
tts: !include yamls/commands_and_notify/tts.yaml
lovelace:
  mode: storage
breaking_changes:
config_check:
browser_mod:
  prefix: "browser_"
  devices:
    dc9bb05e-61b3c9be:
      name: browser_desktop
      disable:
        - light
        - media_player
    8d6fc498-63a52b85:
      name: browser_phone
      disable:
        - light
        - media_player

http:
  cors_allowed_origins: !include cors_allowed_origins.yaml
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5
  trusted_proxies:
    - 127.0.0.1
    - !secret swag_ip
    - !secret trusted_docker_network
    - !secret trusted_home_network
    - !secret authelia_ip
logger:
  default: warning
discovery:
vera:
  vera_controller_url: !secret vera_controller_url
wemo:
  discovery: false
  static:
    - !secret yi_cam_outlet
google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret
ifttt:
  key: !secret ifttt_key
updater:
  include_used_components: true
weather:
  - platform: darksky
    #mode: daily
    api_key: !secret darksky_api_key
speedtestdotnet:
  scan_interval:
    minutes: 15


# Include Folders
automation: !include_dir_merge_list yamls/automation
script: !include_dir_merge_named yamls/scripts
sensor: !include_dir_merge_list yamls/sensors

# Include HA Yamls
binary_sensor: !include yamls/home_assistant_yamls/binary_sensors.yaml
group: !include yamls/home_assistant_yamls/groups.yaml
folder_watcher: !include yamls/home_assistant_yamls/folder_watcher.yaml
zone: !include yamls/home_assistant_yamls/zone.yaml
proximity: !include yamls/home_assistant_yamls/proximity.yaml
coinbase: !include yamls/home_assistant_yamls/coinbase.yaml
plex_assistant: !include yamls/home_assistant_yamls/plex_assistant.yaml

# Commands and Notify
rest_command: !include yamls/commands_and_notify/rest_command.yaml
shell_command: !include yamls/commands_and_notify/shell_commands.yaml
notify: !include yamls/commands_and_notify/notify.yaml
joaoapps_join: !include yamls/commands_and_notify/join.yaml
# intent_script:  !include yamls/commands_and_notify/intent_script.yaml

# Include DBs
recorder: !include yamls/databases/recorder.yaml
history: !include yamls/databases/history.yaml
influxdb: !include yamls/databases/influxdb.yaml
logbook: !include yamls/databases/logbook.yaml
# Front End
panel_iframe: !include yamls/front_end/panel_iframe.yaml

# Include Inputs
input_boolean: !include yamls/inputs/input_boolean.yaml
input_text: !include yamls/inputs/input_text.yaml
input_number: !include yamls/inputs/input_number.yaml
input_select: !include yamls/inputs/input_select.yaml

# Include Devices Yamls
device_tracker: !include yamls/devices/device_tracker.yaml
light: !include yamls/devices/lights.yaml
climate: #!include yamls/devices/climate.yaml
  - platform: honeywell
    username: !secret climate_username
    password: !secret climate_pw
#cast: !include yamls/devices/cast.yaml
#hdmi_cec: !include yamls/devices/cec.yaml
tplink: !include yamls/devices/tplink.yaml
google_assistant: !include yamls/devices/google_assistant.yaml
switch:  !include yamls/devices/switch.yaml
ombi: !include yamls/devices/ombi.yaml
