homeassistant:
  name: Atlanta Condo
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 363
  unit_system: imperial
  time_zone: America/New_York
  customize: !include yamls/front_end/customize.yaml
  whitelist_external_dirs:
    - /config/
    - /
  auth_providers:
    - type: trusted_networks
      allow_bypass_login: true
      trusted_networks:
        - 127.0.0.1
        - !secret trusted_network
        - 172.30.32.0/24
        - !secret trusted_home_network
        - !secret trusted_network2
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password
frontend: !include yamls/front_end/frontend.yaml

config:

websocket_api:

hassio:

browser_mod:
  prefix: "browser_"
  devices:
    180fffa4_a74390c9:
      name: browser_desktop
    f34e5616_7ed10eb1:
      name: browser_phone

http:
  base_url: !secret base_url
  cors_allowed_origins: !include yamls/front_end/cors_allowed_origins.yaml
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - !secret trusted_network
    - !secret desktop_ip
    - !secret hass_ip
    - !secret my_phone_wifi
    - !secret trusted_home_network

api:

logger:
  default: error
  logs:
    homeassistant.components.system_log: fatal
    homeassistant.components.tplink: fatal
    homeassistant.helpers.template: debug
    custom_components.google_keep: fatal
    homeassistant.components.frontend: fatal
    frontend: fatal
    homeassistant.components.tautulli: fatal
    pytautulli : fatal

lovelace:
  mode: yaml

system_health:

discovery:
  ignore:
    - roku
    - google_cast
    - plex_mediaserver
    - igd

tts: !include yamls/commands_and_notify/tts.yaml

sun:

vera:
  vera_controller_url: !secret vera_controller_url
  exclude: [58]

wemo:
  discovery: true
  static:
    - !secret yi_cam_outlet

google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

ifttt:
  key: !secret ifttt_key

updater:
  include_used_components: true

weather:
  - platform: darksky
    mode: daily
    api_key: !secret darksky_api_key

speedtestdotnet:
  scan_interval:
    minutes: 15

# Include Folders
automation: !include_dir_merge_list yamls/automation
script: !include_dir_merge_named yamls/scripts
sensor: !include_dir_merge_list yamls/sensors

# Include HA Yamls
binary_sensor: !include yamls/home_assistant_yamls/binary_sensors.yaml
group: !include yamls/home_assistant_yamls/groups.yaml
folder_watcher: !include yamls/home_assistant_yamls/folder_watcher.yaml
zone: !include yamls/home_assistant_yamls/zone.yaml
proximity: !include yamls/home_assistant_yamls/proximity.yaml
iqvia: !include yamls/home_assistant_yamls/iqvia.yaml
coinbase: !include yamls/home_assistant_yamls/coinbase.yaml

# Commands and Notify
rest_command: !include yamls/commands_and_notify/rest_command.yaml
shell_command: !include yamls/commands_and_notify/shell_commands.yaml
notify: !include yamls/commands_and_notify/notify.yaml
joaoapps_join: !include yamls/commands_and_notify/join.yaml

# Include Front End
weblink: !include yamls/front_end/weblink.yaml
# google_domains: !include yamls/front_end/google_domains.yaml

# Include DBs
recorder: !include yamls/databases/recorder.yaml
logbook: !include yamls/databases/logbook.yaml
history: !include yamls/databases/history.yaml
influxdb: !include yamls/databases/influxdb.yaml

# Include Inputs
input_boolean: !include yamls/inputs/input_boolean.yaml
input_text: !include yamls/inputs/input_text.yaml
input_number: !include yamls/inputs/input_number.yaml
input_select: !include yamls/inputs/input_select.yaml

# Include Devices Yamls
device_tracker: !include yamls/devices/device_tracker.yaml
light: !include yamls/devices/lights.yaml
climate: !include yamls/devices/climate.yaml
dyson: !include yamls/devices/dyson.yaml
mqtt: !include yamls/devices/mqtt.yaml
cast: !include yamls/devices/cast.yaml
hdmi_cec: !include yamls/devices/cec.yaml
tplink: !include yamls/devices/tplink.yaml
tuya: !include yamls/devices/tuya.yaml
google_assistant: !include yamls/devices/google_assistant.yaml
switch:  !include yamls/devices/switch.yaml
lock:  !include yamls/devices/lock.yaml
nzbget: !include yamls/devices/nzbget.yaml
googlehome: !include yamls/devices/google_home.yaml