resources: !include lovelace/global_cards/resources.yaml
popup_cards: !include lovelace/global_cards/pop_up_cards.yaml
button_card_templates: !include lovelace/global_cards/button_card_templates.yaml
title: Home Control
custom_header:
  button_text:
    options: '{{ time }}'
  hide_unused: true
  voice_hide: true
  menu_hide: false
  hide_config: true
  hide_raw: true
  hide_help: true
  active_tab_color: rgb(19, 172, 198)
  show_tabs: 0,1,2,3
  compact_mode: true
  hidden_tab_redirect: false
  exceptions:
    - conditions:
        query_string: kiosk
      config:
        kiosk_mode: true
  shadow: true
swipe_nav:
  wrap: true
  animate: swipe
  skip_tabs: 4,5
  prevent_default: true
  swipe_amount: 15
views:
  - !include lovelace/00_main_view.yaml
  - !include lovelace/01_media_player_view.yaml
  - !include lovelace/02_calendar_view.yaml
  - !include lovelace/03_system_view.yaml
  - !include lovelace/04_system_monitor_view.yaml
  - !include lovelace/05_tautulli_watch_history.yaml