title: Atlanta Condo
resources:
  - url: /local/button-card.js
    type: module
  - url: /local/custom_ui/weather-card.js
    type: js
views:
  - badges:
      - device_tracker.neil
      - device_tracker.butters
      - sensor.tautulli_total
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_temperature
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daytime_high_temperature_0
      - sensor.dark_sky_overnight_low_temperature_0
      - sensor.forecast_icon
      - sensor.daylight_remaining_hm
    cards:
      - cards:
          - cards:
              - entity: light.kitchen
                type: light
              - entity: light.bed
                type: light
              - entity: switch.furnace_switch_29
                state_image:
                  'off': /local/furnace-off.png
                  'on': /local/furnace.png
                tap_action:
                  action: toggle
                type: picture-entity
            type: horizontal-stack
          - cards:
              - entity: switch.bathroom_light
                state_image:
                  'off': /local/input_boolean_icons/bathroom-light-off.png
                  'on': /local/input_boolean_icons/bathroom-light-on.png
                tap_action:
                  action: toggle
                type: picture-entity
              - entity: switch.bathroom_fan
                state_image:
                  'off': /local/input_boolean_icons/fan-off.png
                  'on': /local/input_boolean_icons/fan-on.png
                tap_action:
                  action: toggle
                type: picture-entity
              - entity: switch.lamp
                state_image:
                  'off': /local/lamp-off.jpg
                  'on': /local/lamp.jpg
                tap_action:
                  action: toggle
                type: picture-entity
            type: horizontal-stack
        type: vertical-stack
      - entities:
          - input_select.couch_color
        show_header_toggle: false
        title: Couch Lights
        type: entities
      - card:
          entities:
            - input_text.couch_color
            - input_number.couch_r
            - input_number.couch_g
            - input_number.couch_b
          type: entities
        conditions:
          - entity: light.couch
            state: 'on'
        type: conditional
      - entity: climate.thermostat
        type: thermostat
      - entities:
          - lock.schlage_deadbolt_47
        show_header_toggle: false
        title: Lock
        type: entities
      - cards:
          - cards:
              - entity: input_boolean.weather_notifications
                state_image:
                  'off': /local/input_boolean_icons/weather-notify-off.png
                  'on': /local/input_boolean_icons/weather-notify-on.png
                tap_action:
                  action: toggle
                  service_data: input_boolean.weather_notifications
                type: picture-entity
              - entity: input_boolean.notifications_on
                state_image:
                  'off': /local/input_boolean_icons/bell-off.png
                  'on': /local/input_boolean_icons/bell-on.png
                tap_action:
                  action: toggle
                type: picture-entity
              - entity: input_boolean.presence_automations
                state_image:
                  'off': /local/input_boolean_icons/home-off.png
                  'on': /local/input_boolean_icons/home-on.png
                tap_action:
                  action: toggle
                type: picture-entity
              - entity: switch.space_heater_35
                state_image:
                  'off': /local/input_boolean_icons/heater-off.png
                  'on': /local/input_boolean_icons/heater-on.png
                tap_action:
                  action: toggle
                type: picture-entity
            type: horizontal-stack
          - cards:
              - entity: input_boolean.parents_lock_code
                state_image:
                  'off': /local/mom-dad-away.jpg
                  'on': /local/mom-dad.jpg
                tap_action:
                  action: toggle
                type: picture-entity
              - entity: input_boolean.autolock
                state_image:
                  'off': /local/input_boolean_icons/lock-smart-off.png
                  'on': /local/input_boolean_icons/lock-smart-on.png
                tap_action:
                  action: toggle
                type: picture-entity
              - entity: switch.yi_power
                state_image:
                  'off': /local/input_boolean_icons/webcam-off.png
                  'on': /local/input_boolean_icons/webcam-on.png
                tap_action:
                  action: toggle
                type: picture-entity
              - entity: input_boolean.butters_home
                state_image:
                  'off': /local/butters-away.jpg
                  'on': /local/butters.jpg
                tap_action:
                  action: toggle
                type: picture-entity
            type: horizontal-stack
        show_header_toggle: false
        type: vertical-stack
      - cards:
          - entities:
              - sensor.dark_sky_summary
              - sensor.dark_sky_minutely_summary
              - sensor.dark_sky_hourly_summary
              - sensor.dark_sky_daily_summary
            show_header_toggle: false
            title: Weather Summary
            type: entities
          - entity: weather.dark_sky
            type: weather-forecast
        type: vertical-stack
    icon: 'mdi:home'
    path: default_view
    title: Home
  - badges:
      - sensor.tautulli_direct_play
      - sensor.tautulli_direct_stream
      - sensor.tautulli_total
      - sensor.tautulli_total_bandwidth
      - sensor.tautulli_transcode
    cards:
      - entities:
          - input_boolean.tv_power
          - scene.theater_mode
          - input_text.gh_speak
        show_header_toggle: false
        title: TV Inputs
        type: entities
      - card:
          entities:
            - script.tv_input_chromecast
            - script.tv_input_playstation
          type: entities
        conditions:
          - entity: input_boolean.tv_power
            state: 'on'
        type: conditional
      - entity: media_player.kitchen_home
        type: media-control
      - entity: media_player.living_room_tv
        type: media-control
      - entities:
          - input_text.broadcast_message
          - input_text.google_command
        show_header_toggle: false
        title: Google Assistant
        type: entities
      - entities:
          - sensor.watching_plex
        show_header_toggle: false
        title: Watching Plex
        type: entities
      - entities:
          - sensor.sonarr_upcoming_list
          - sensor.radarr_upcoming_list
        show_header_toggle: false
        title: Downloaders
        type: entities
      - entities:
          - sensor.desktop_disk_space_c
          - sensor.desktop_disk_space_e
          - sensor.desktop_disk_space_f
          - sensor.desktop_disk_space_i
          - sensor.desktop_disk_space_j
        show_header_toggle: false
        title: Desktop Disk Space
        type: entities
      - entities:
          - media_player.plex_web_chrome
          - media_player.plex_pixel_2_xl
          - media_player.plex_pixel_2_xl_2
          - media_player.plex_plex_web_chrome
          - media_player.plex_desktop
          - media_player.tablet_living_room_plex
          - media_player.plex_galaxy_note8
        state_filter:
          - playing
        type: entity-filter
    icon: 'mdi:video'
    path: media_players
    title: Media Players
  - badges: []
    cards:
      - entities:
          - sensor.steps
          - sensor.distance
          - sensor.floors
          - sensor.activity_calories
          - sensor.calories
          - sensor.calories_bmr
          - sensor.time_very_active
          - sensor.time_fairly_active
          - sensor.time_lightly_active
          - sensor.time_sedentary
          - sensor.resting_heart_rate
        show_header_toggle: false
        title: Activity
        type: entities
      - entities:
          - sensor.sleep_efficiency
          - sensor.sleep_time_asleep
          - sensor.sleep_time_awake
          - sensor.sleep_time_to_fall_asleep
          - sensor.sleep_start_time
          - sensor.sleep_time_in_bed_hours
          - sensor.time_after_wakeup
          - sensor.awakenings_count
        show_header_toggle: false
        title: Sleep
        type: entities
      - entities:
          - sensor.weight
          - sensor.bmi
          - sensor.body_fat
          - sensor.aria_battery
          - sensor.charge_2_battery
        show_header_toggle: false
        title: Miscellaneous
        type: entities
    icon: 'mdi:heart-pulse'
    path: health
    title: FitBit
  - badges:
      - device_tracker.neil
      - device_tracker.neil_bluetooth
      - device_tracker.neil_wifi
      - device_tracker.neil_pixel_tasker
      - device_tracker.monitor_neil
      - device_tracker.gina
      - device_tracker.parents
      - device_tracker.butters
    cards:
      - entities:
          - sensor.dark_sky_temperature
          - sensor.dark_sky_apparent_temperature
          - sensor.dark_sky_daytime_high_temperature_0
          - sensor.dark_sky_overnight_low_temperature_0
          - sensor.dark_sky_daytime_high_apparent_temperature_0
          - sensor.dark_sky_overnight_low_apparent_temperature_0
          - sensor.dark_sky_precip_intensity
          - sensor.dark_sky_precip_probability
          - sensor.dark_sky_wind_speed
          - sensor.dark_sky_nearest_storm_distance
          - sensor.dark_sky_humidity
          - sensor.dark_sky_visibility
          - sensor.dark_sky_cloud_coverage
          - sensor.dark_sky_moon_phase_0
          - sensor.allergy_index_today_2
        show_header_toggle: false
        title: Weather
        type: glance
      - entities:
          - sensor.dark_sky_summary
          - sensor.dark_sky_minutely_summary
          - sensor.dark_sky_hourly_summary
          - sensor.dark_sky_daily_summary
        show_header_toggle: false
        title: Weather Summary
        type: entities
      - entities:
          - sensor.memory_free
          - sensor.memory_use
          - sensor.memory_use_percent
          - sensor.processor_use
          - sensor.network_in_eth0
          - sensor.disk_use_percent_
          - sensor.network_out_eth0
          - sensor.last_boot
          - sensor.since_last_boot_templated
          - sensor.ha_uptime
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
        show_header_toggle: false
        title: System Monitor
        type: glance
      - entities:
          - sensor.pi_zero_cpu_temp
          - sensor.pi_zero_cpu_usage
          - sensor.pi_zero_disk_usage
          - sensor.pi_zero_uptime
        show_header_toggle: false
        title: Pi Zero System
        type: glance
      - entities:
          - script.restart_homeassistant
          - script.system_reboot
          - script.reboot_pi_zero
        show_header_toggle: false
        title: System Control
        type: entities
      - cards:
          - entities:
              - sensor.last_lock_code_name
              - sensor.lock_battery_level
              - entity: input_boolean.temp_lock_code_set
                icon: mdi:lock
                tap_action:
                  action: toggle
            type: glance
          - entities:
              - input_text.lock_code_temp
            type: entities
        show_header_toggle: false
        title: Lock Code
        type: vertical-stack
      - entities:
          - sensor.template_calendar_events
          - sensor.template_calendar_family_birthdays
          - sensor.template_calendar_friend_birthdays
          - sensor.template_calendar_facebook_events
        show_header_toggle: false
        title: Calendar List
        type: entities
    icon: 'mdi:desktop-classic'
    path: all_sensors
    title: Sensors
