resources:
  - type: module
    url: /local/button-card.js?v=0.0.3
  - type: js
    url: /local/weather-card.js
  - type: js
    url: /local/tracker-card.js?v=0.1.5
  - type: js
    url: /local/custom-lovelace/monster-card/monster-card.js?v=0.2.3
  - type: module
    url: /local/custom-lovelace/thermostat-card/thermostat-card.js?v=0.1.1
  - type: js
    url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.3.3
  - type: js
    url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.1.4
title: Atlanta Condo
views:
  - badges:
      - device_tracker.neil
      - device_tracker.butters
      - sensor.tautulli_total
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_temperature
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daytime_high_temperature_0
      - sensor.dark_sky_overnight_low_temperature_0
      - sensor.forecast_icon
      - sensor.daylight_remaining_hm
    cards:
      - type: custom:compact-custom-header
      - cards:
          - cards:
              - entity: light.kitchen
                type: light
              - entity: light.bed
                type: light
            type: horizontal-stack
          - cards:
              - entity: switch.furnace_switch_29
                state_image:
                  'off': /local/furnace-off.png
                  'on': /local/furnace.png
                tap_action:
                  action: toggle
                type: picture-entity
              - entity: switch.lamp
                state_image:
                  'off': /local/lamp-off.jpg
                  'on': /local/lamp.jpg
                tap_action:
                  action: toggle
                type: picture-entity
            type: horizontal-stack
          - cards:
              - action: toggle
                card_style: ''
                color: 'rgb(57, 111, 182)'
                color_off: 'rgb(181, 181, 181)'
                color_type: icon
                default_color: var(--primary-text-color)
                entity: switch.bathroom_light
                icon: 'mdi:toilet'
                name: Bathroom Light
                size: 40%
                type: 'custom:button-card'
              - action: toggle
                card_style: ''
                color: 'rgb(57, 111, 182)'
                color_off: 'rgb(181, 181, 181)'
                color_type: icon
                default_color: var(--primary-text-color)
                entity: switch.bathroom_fan
                icon: 'mdi:fan'
                name: Bathroom Fan
                size: 40%
                type: 'custom:button-card'
            type: horizontal-stack
        type: vertical-stack
      - type: 'custom:button-card'
        action: toggle
        color: 'auto'
        color_off: 'rgb(181, 181, 181)'
        color_type: icon
        entity: light.couch
        icon: 'mdi:sofa'
        name: Couch Light
        size: 40%
      - type: conditional
        conditions:
          - entity: light.couch
            state: 'on'
        card:
          type: vertical-stack
          cards:
            - type: horizontal-stack
              cards:
                - type: 'custom:button-card'
                  action: service
                  service:
                    domain: scene
                    action: turn_on
                    data:
                      entity_id: scene.couch_white
                  color: 'rgb(255, 255, 255)'
                  color_type: icon
                  icon: 'mdi:sofa'
                  name: White
                - type: 'custom:button-card'
                  action: service
                  service:
                    domain: scene
                    action: turn_on
                    data:
                      entity_id: scene.couch_soft_white
                  color: 'rgb(255, 242, 230)'
                  color_type: icon
                  icon: 'mdi:sofa'
                  name: Soft White
                - type: 'custom:button-card'
                  action: service
                  service:
                    domain: scene
                    action: turn_on
                    data:
                      entity_id: scene.couch_blue
                  color: 'rgb(0, 0, 255)'
                  color_type: icon
                  icon: 'mdi:sofa'
                  name: Blue
            - type: horizontal-stack
              cards:
                - type: 'custom:button-card'
                  action: service
                  service:
                    domain: scene
                    action: turn_on
                    data:
                      entity_id: scene.couch_red
                  color: 'rgb(255, 0, 0)'
                  color_type: icon
                  icon: 'mdi:sofa'
                  name: Red
                - type: 'custom:button-card'
                  action: service
                  service:
                    domain: scene
                    action: turn_on
                    data:
                      entity_id: scene.couch_green
                  color: 'rgb(0, 255, 0)'
                  color_type: icon
                  icon: 'mdi:sofa'
                  name: Green
                - type: 'custom:button-card'
                  action: service
                  service:
                    domain: scene
                    action: turn_on
                    data:
                      entity_id: scene.couch_purple
                  color: 'rgb(255, 0, 255)'
                  color_type: icon
                  icon: 'mdi:sofa'
                  name: Purple
            - type: entities
              entities:
                - input_text.couch_color
                - input_number.couch_r
                - input_number.couch_g
                - input_number.couch_b
      - cards:
          - cards:
              - entity: climate.thermostat
                name: Thermostat
                type: thermostat
            type: horizontal-stack
          - cards:
              - action: toggle
                card_style: ''
                color: 'rgb(57, 111, 182)'
                color_off: 'rgb(181, 181, 181)'
                color_type: icon
                default_color: var(--primary-text-color)
                entity: switch.lock_switch
                icon: attribute
                name: Lock
                size: 40%
                type: 'custom:button-card'
            type: horizontal-stack
          - cards:
              - action: toggle
                card_style: ''
                color: 'rgb(57, 111, 182)'
                color_off: 'rgb(181, 181, 181)'
                color_type: icon
                default_color: var(--primary-text-color)
                entity: input_boolean.weather_notifications
                icon: 'mdi:white-balance-sunny'
                name: Weather
                size: 40%
                type: 'custom:button-card'
              - action: toggle
                card_style: ''
                color: 'rgb(57, 111, 182)'
                color_off: 'rgb(181, 181, 181)'
                color_type: icon
                default_color: var(--primary-text-color)
                entity: input_boolean.notifications_on
                icon: 'mdi:bell'
                name: Notifications
                size: 40%
                type: 'custom:button-card'
              - action: toggle
                card_style: ''
                color: 'rgb(57, 111, 182)'
                color_off: 'rgb(181, 181, 181)'
                color_type: icon
                default_color: var(--primary-text-color)
                entity: input_boolean.presence_automations
                icon: 'mdi:home'
                name: Presence
                size: 40%
                type: 'custom:button-card'
              - action: toggle
                card_style: ''
                color: 'rgb(57, 111, 182)'
                color_off: 'rgb(181, 181, 181)'
                color_type: icon
                default_color: var(--primary-text-color)
                entity: switch.space_heater_35
                icon: 'mdi:home'
                name: Space Heater
                size: 40%
                type: 'custom:button-card'
            type: horizontal-stack
          - cards:
              - action: toggle
                card_style: ''
                color: 'rgb(57, 111, 182)'
                color_off: 'rgb(181, 181, 181)'
                color_type: icon
                default_color: var(--primary-text-color)
                entity: input_boolean.parents_lock_code
                icon: 'mdi:human-female-boy'
                name: Parents Code
                size: 40%
                type: 'custom:button-card'
              - action: toggle
                card_style: ''
                color: 'rgb(57, 111, 182)'
                color_off: 'rgb(181, 181, 181)'
                color_type: icon
                default_color: var(--primary-text-color)
                entity: input_boolean.autolock
                icon: 'mdi:lock-smart'
                name: Autolock
                size: 40%
                type: 'custom:button-card'
              - action: toggle
                card_style: ''
                color: 'rgb(57, 111, 182)'
                color_off: 'rgb(181, 181, 181)'
                color_type: icon
                default_color: var(--primary-text-color)
                entity: switch.yi_power
                icon: 'mdi:webcam'
                name: Camera
                size: 40%
                type: 'custom:button-card'
              - action: toggle
                card_style: ''
                color: 'rgb(57, 111, 182)'
                color_off: 'rgb(181, 181, 181)'
                color_type: icon
                default_color: var(--primary-text-color)
                entity: input_boolean.butters_home
                icon: 'mdi:dog-side'
                name: Butters
                size: 40%
                type: 'custom:button-card'
            type: horizontal-stack
        type: vertical-stack
      - cards:
          - entities:
              - sensor.dark_sky_summary
              - sensor.dark_sky_minutely_summary
              - sensor.dark_sky_hourly_summary
              - sensor.dark_sky_daily_summary
            show_header_toggle: false
            title: Weather Summary
            type: entities
          - entity: weather.dark_sky
            type: weather-forecast
        type: vertical-stack
    icon: 'mdi:home'
    path: default_view
    title: Home
  - badges:
      - sensor.tautulli_direct_play
      - sensor.tautulli_direct_stream
      - sensor.tautulli_total
      - sensor.tautulli_total_bandwidth
      - sensor.tautulli_transcode
    cards:
      - entities:
          - input_boolean.tv_power
          - scene.theater_mode
          - input_text.gh_speak
        show_header_toggle: false
        title: TV Inputs
        type: entities
      - type: conditional
        conditions:
          - entity: input_boolean.tv_power
            state: 'on'
        card:
          type: horizontal-stack
          cards:
            - type: 'custom:button-card'
              action: service
              service:
                domain: script
                action: trigger
                data:
                  entity_id: script.tv_input_chromecast
              color_type: icon
              icon: 'mdi:cast'
              name: Chromecast
            - type: 'custom:button-card'
              action: service
              service:
                domain: script
                action: trigger
                data:
                  entity_id: script.tv_input_playstation
              color_type: icon
              icon: 'mdi:playstation'
              name: Playstation
      - entity: media_player.kitchen_home
        type: media-control
      - entity: media_player.living_room_tv
        type: media-control
      - entities:
          - input_text.broadcast_message
          - input_text.google_command
        show_header_toggle: false
        title: Google Assistant
        type: entities
      - entities:
          - sensor.watching_plex
        show_header_toggle: false
        title: Watching Plex
        type: entities
      - entities:
          - sensor.desktop_disk_space_c
          - sensor.desktop_disk_space_e
          - sensor.desktop_disk_space_f
          - sensor.desktop_disk_space_i
          - sensor.desktop_disk_space_j
        show_header_toggle: false
        title: Desktop Disk Space
        type: entities
      - entities:
          - media_player.plex_web_chrome
          - media_player.plex_pixel_2_xl
          - media_player.plex_pixel_2_xl_2
          - media_player.plex_plex_web_chrome
          - media_player.plex_desktop
          - media_player.tablet_living_room_plex
          - media_player.plex_galaxy_note8
        state_filter:
          - playing
        type: entity-filter
        show_empty: false
      - type: custom:upcoming-media-card
        entity: sensor.sonarr_upcoming_media
        title: Upcoming TV
      - type: custom:upcoming-media-card
        entity: sensor.radarr_upcoming_media
        title: Upcoming Movies
      - type: custom:upcoming-media-card
        entity: sensor.plex_recently_added
        title: Recently Downloaded
    icon: 'mdi:video'
    path: media_players
    title: Media Players
  - badges: []
    cards:
      - entities:
          - sensor.steps
          - sensor.distance
          - sensor.floors
          - sensor.activity_calories
          - sensor.calories
          - sensor.calories_bmr
          - sensor.time_very_active
          - sensor.time_fairly_active
          - sensor.time_lightly_active
          - sensor.time_sedentary
          - sensor.resting_heart_rate
        show_header_toggle: false
        title: Activity
        type: entities
      - entities:
          - sensor.sleep_efficiency
          - sensor.sleep_time_asleep
          - sensor.sleep_time_awake
          - sensor.sleep_time_to_fall_asleep
          - sensor.sleep_start_time
          - sensor.sleep_time_in_bed_hours
          - sensor.time_after_wakeup
          - sensor.awakenings_count
        show_header_toggle: false
        title: Sleep
        type: entities
      - entities:
          - sensor.weight
          - sensor.bmi
          - sensor.body_fat
          - sensor.aria_battery
          - sensor.charge_2_battery
        show_header_toggle: false
        title: Miscellaneous
        type: entities
    icon: 'mdi:heart-pulse'
    path: health
    title: FitBit
  - badges:
      - device_tracker.neil
      - device_tracker.neil_bluetooth
      - device_tracker.neil_wifi
      - device_tracker.neil_pixel_tasker
      - device_tracker.monitor_neil
      - device_tracker.gina
      - device_tracker.parents
      - device_tracker.butters
    cards:
      - entities:
          - sensor.dark_sky_temperature
          - sensor.dark_sky_apparent_temperature
          - sensor.dark_sky_daytime_high_temperature_0
          - sensor.dark_sky_overnight_low_temperature_0
          - sensor.dark_sky_daytime_high_apparent_temperature_0
          - sensor.dark_sky_overnight_low_apparent_temperature_0
          - sensor.dark_sky_precip_intensity
          - sensor.dark_sky_precip_probability
          - sensor.dark_sky_wind_speed
          - sensor.dark_sky_nearest_storm_distance
          - sensor.dark_sky_humidity
          - sensor.dark_sky_visibility
          - sensor.dark_sky_cloud_coverage
          - sensor.dark_sky_moon_phase_0
          - sensor.allergy_index_today_2
        title: Weather
        type: glance
      - entities:
          - sensor.dark_sky_summary
          - sensor.dark_sky_minutely_summary
          - sensor.dark_sky_hourly_summary
          - sensor.dark_sky_daily_summary
        show_header_toggle: false
        title: Weather Summary
        type: entities
      - entities:
          - sensor.template_calendar_events
          - sensor.template_calendar_family_birthdays
          - sensor.template_calendar_friend_birthdays
          - sensor.template_calendar_facebook_events
        show_header_toggle: false
        title: Calendar List
        type: entities
      - cards:
          - cards:
              - entities:
                  - sensor.last_lock_code_name
                  - sensor.lock_battery_level
                type: glance
            type: horizontal-stack
          - cards:
              - action: toggle
                card_style: ''
                color: 'rgb(57, 111, 182)'
                color_off: 'rgb(181, 181, 181)'
                color_type: icon
                default_color: var(--primary-text-color)
                entity: input_boolean.temp_lock_code_set
                icon: 'mdi:lock'
                name: Temp Code
                size: 32%
                type: 'custom:button-card'
            type: horizontal-stack
          - cards:
              - entities:
                  - input_text.lock_code_temp
                type: entities
            type: horizontal-stack
        type: vertical-stack
    icon: 'mdi:calendar-today'
    path: weather_and_calendar
    title: General
  - badges: []
    cards:
      - cards:
          - cards:
              - entities:
                  - sensor.memory_free
                  - sensor.memory_use
                  - sensor.network_in_eth0
                  - sensor.network_out_eth0
                  - sensor.last_boot
                  - sensor.since_last_boot_templated
                  - sensor.ha_uptime
                  - sensor.speedtest_download
                  - sensor.speedtest_upload
                  - sensor.speedtest_ping
                title: Pi System Monitor
                type: glance
            type: horizontal-stack
          - cards:
              - entity: sensor.memory_use_percent
                name: Pi Memory Usage
                type: gauge
            type: horizontal-stack
          - cards:
              - entity: sensor.processor_use
                name: Pi Processor Use
                type: gauge
            type: horizontal-stack
          - cards:
              - entity: sensor.disk_use_percent_
                name: Pi Disk Usage
                type: gauge
            type: horizontal-stack
        type: vertical-stack
      - cards:
          - cards:
              - entities:
                  - sensor.pi_zero_cpu_temp
                  - sensor.pi_zero_uptime
                  - sensor.speedtest_ping
                title: Pi Zero System Monitor
                type: glance
            type: horizontal-stack
          - cards:
              - entity: sensor.pi_zero_cpu_usage
                name: Pi Zero CPU Usage
                type: gauge
            type: horizontal-stack
          - cards:
              - entity: sensor.pi_zero_disk_usage
                name: Pi Zero Disk Usage
                type: gauge
            type: horizontal-stack
        type: vertical-stack
      - entities:
          - script.restart_homeassistant
          - script.system_reboot
          - script.reboot_pi_zero
        show_header_toggle: false
        title: System Control
        type: entities
      - title: null
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
          - sensor.custom_python_script_tracker
        type: 'custom:tracker-card'
    icon: 'mdi:desktop-classic'
    path: system_monitor
    title: System
