resources: !include lovelace/resources.yaml
popup_cards: !include lovelace/pop_up_cards.yaml
title: Atlanta Condo
views:
  - !include lovelace/00_main_view.yaml
  - !include lovelace/01_media_player_view.yaml
  - !include lovelace/02_weather_and_calendar_view.yaml
  - !include lovelace/03_system_view.yaml
  - !include lovelace/04_system_monitor_view.yaml