- id: couch_lights_bulb_color_light_already_on
  alias: 'Couch Lights Bulb Color'
  initial_state: false
  trigger:
    platform: state
    entity_id: input_select.couch_color
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.couch_light_script_running
      state: 'off'
  action:
    - service: script.couch_light_scripts_trigger

- id: couch_color_slider
  alias: 'Couch Color Slider'
  initial_state: false
  trigger:
  - platform: state
    entity_id: input_number.couch_r
  - platform: state
    entity_id: input_number.couch_g
  - platform: state
    entity_id: input_number.couch_b
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.couch_light_script_running
      state: 'off'
  action:
    service: script.couch_color_input_numbers

- id: couch_lights_sensor_changed
  alias: 'Couch Lights Sensor Changed'
  initial_state: false
  trigger:
    platform: state
    entity_id: sensor.couch_light_color_name
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.couch_light_script_running
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.couch_light_script_running
    - service: script.couch_light_update_all_controls

- id: couch_light_set_input_text
  alias: 'Couch Lights Set Input Text'
  initial_state: false
  trigger:
    - platform: state
      entity_id: input_text.couch_color
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.couch_light_script_running
      state: 'off'
  action:
    service: script.couch_color_name_from_input_text

- id: couch_color_google_voice
  alias: 'Couch Color Google Voice'
  initial_state: false
  trigger:
    - platform: state
      entity_id: sensor.couch_light_color
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.couch_light_script_running
      state: 'off'
    - condition: state
      entity_id: light.couch
      state: 'on'
  action:
    service: script.couch_color_google_voice

- id: couch_group_toggle_visibility
  alias: 'Couch Group Toggle Visibility'
  initial_state: false
  trigger:
    platform: state
    entity_id: light.couch
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.couch_group_toggle_visibility