- id: couch_lights_sensor_changed
  alias: 'Couch Lights Sensor Changed'
  trigger:
    platform: state
    entity_id: sensor.couch_light_color
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.couch_light_update_input_text

- id: couch_light_set_input_text
  alias: 'Couch Lights Set Input Text'
  trigger:
    - platform: state
      entity_id: input_text.couch_color
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: light.couch
      state: 'on'
    - condition: template
      value_template: "{{(as_timestamp(now()) - (as_timestamp(states.sensor.couch_light_color.last_changed))>10)}}"
  action:
    service: script.couch_color_name_from_input_text