- id: google_home_talk
  alias: 'Google Home Talk'
  trigger:
    - platform: state
      entity_id: input_text.gh_speak
  condition:
    - condition: template
      value_template: "{{ not is_state('input_text.gh_speak', ' ') }}"
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: tts.google_say
      entity_id: media_player.kitchen_display
      data_template:
        message: "{{states('input_text.gh_speak')}}."
    - delay: 00:00:02
    - service: input_text.set_value
      data:
        entity_id: input_text.gh_speak
        value: ' '