- id: kitchen_lights_on
  alias: 'Kitchen Lights On'
  initial_state: false
  trigger:
    - platform: state
      entity_id: light.front_kitchen_6
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: light.back_kitchen_7
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: switch.furnace_switch_9
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: light.kitchen
      to: 'on'
      from: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.kitchen_light_script_running
      state: 'off'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.kitchen

- id: kitchen_lights_off
  alias: 'Kitchen Lights Off'
  initial_state: false
  trigger:
    - platform: state
      entity_id: light.front_kitchen_6
      to: 'off'
      from: 'on'
    - platform: state
      entity_id: light.back_kitchen_7
      to: 'off'
      from: 'on'
    - platform: state
      entity_id: switch.furnace_switch_9
      to: 'off'
      from: 'on'
    - platform: state
      entity_id: light.kitchen
      to: 'off'
      from: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.kitchen_light_script_running
      state: 'off'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.kitchen

- id: kitchen_lights_on_when_dark_out
  alias: 'Kitchen Lights On When Dark Out'
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.dark_out
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: group.kitchenlights
      state: 'off'  
    - condition: state
      entity_id: input_boolean.kitchen_light_script_running
      state: 'off'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'on'
    - condition: time
      after: '08:00:00'
      before: '22:00:00'
  action:
    - service: light.turn_on
      entity_id: light.kitchen

- id: bathroom_fan_off_after_1_hour
  alias: 'Bathroom Fan Off After 1 Hour'
  initial_state: false
  trigger:
    platform: state
    entity_id: switch.bathroom_fan
    to: 'on'
    for:
      hours: 1
  action:
    - service: switch.turn_off
      entity_id: group.bathroom