- id: kitchen_lights_on
  alias: 'Kitchen Lights On'
  trigger:
    - platform: state
      entity_id: light.front_kitchen_31
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: light.back_kitchen_30
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: switch.furnace_switch_29
      to: 'on'
      from: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
    - condition: state
      entity_id: input_boolean.kitchen_lights_running
      state: 'off'
  action:
    - service: script.kitchen_lights_on

- id: kitchen_lights_off
  alias: 'Kitchen Lights Off'
  trigger:
    - platform: state
      entity_id: light.front_kitchen_31
      to: 'off'
      from: 'on'
    - platform: state
      entity_id: light.back_kitchen_30
      to: 'off'
      from: 'on'
    - platform: state
      entity_id: switch.furnace_switch_29
      to: 'off'
      from: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
    - condition: state
      entity_id: input_boolean.kitchen_lights_running
      state: 'off'
  action:
    - service: script.kitchen_lights_off

- id: kitchen_lights_on_when_dark_out
  alias: 'Kitchen Lights On When Dark Out'
  trigger:
    platform: state
    entity_id: binary_sensor.dark_out
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: light.kitchen
      state: 'off'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'on'
    - condition: time
      after: '08:00:00'
      before: '22:00:00'
    - condition: state
      entity_id: input_boolean.kitchen_lights_running
      state: 'off'
  action:
    - service: script.kitchen_lights_on

- id: kitchen_lights_off_when_not_dark_out
  alias: 'Kitchen Lights Off When Not Dark Out'
  trigger:
    platform: numeric_state
    entity_id: sensor.illuminance
    above: '7000'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: light.kitchen
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'on'
    - condition: state
      entity_id: input_boolean.kitchen_lights_running
      state: 'off'
  action:
    - service: script.kitchen_lights_off

- id: bathroom_fan_off_after_1_hour
  alias: 'Bathroom Fan Off After 1 Hour'
  trigger:
    platform: state
    entity_id: switch.bathroom_fan
    to: 'on'
    for:
      hours: 1
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: group.bathroom