# Lock Battery Level
- id: lock_battery_low_notify
  alias: 'Lock Battery Low Notify'
  trigger:
    platform: numeric_state
    entity_id: sensor.lock_battery_level
    below: '50'
    above: '25'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.notify_lock_battery_low
          
- id: lock_battery_very_low_notify
  alias: 'Lock Battery Very Low Notify'
  trigger:
    platform: numeric_state
    entity_id: sensor.lock_battery_level
    below: '25'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.notify_lock_battery_very_low

# Notify if unlocked without code
- id: lock_door_unlocked_notify_unknown_code
  alias: 'Lock Door Unlocked Notify Unknown Code'
  trigger:
    platform: state
    entity_id: input_boolean.door_open
    to: 'on'
    for:
      seconds: 20
  condition:
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'off'
  action:
    - service: script.notify_lock_unlocked_unknown_code

# Lock Pin Entered
- id: lock_code_entered
  alias: 'Lock Code Entered'
  trigger:
    - platform: state
      entity_id: binary_sensor.lock_code_entered
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'off'
  action:
    - service: script.presence_lock_code_entered_not_family

# Auto Lock
- id: lock_door_auto_lock
  alias: 'Lock Door Auto Lock'
  trigger:
    - platform: state
      entity_id: lock.schlage_deadbolt_91
      to: 'unlocked'
      from: 'locked'
      for:
        seconds: 20
    - platform: state
      entity_id: input_boolean.door_open
      to: 'on'
      for:
        seconds: 20
  condition:
    - condition: state
      entity_id: input_boolean.autolock
      state: 'on'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - delay: 00:00:10
    - condition: state
      entity_id: input_boolean.autolock
      state: 'on'
    - service: script.lock_auto_lock_door


- id: lock_auto_lock_door_switch_on
  alias: 'Lock Auto Lock Door Switch On'
  trigger:
    platform: state
    entity_id: input_boolean.autolock
    to: 'on'
    from: 'off'
  condition:
    - condition: state
      entity_id: lock.schlage_deadbolt_91
      state: 'unlocked'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.lock_auto_lock_door_on

- id: lock_auto_lock_door_switch_off
  alias: 'Lock Auto Lock Door Switch Off'
  trigger:
    platform: state
    entity_id: input_boolean.autolock
    to: 'off'
    from: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.lock_auto_lock_door_off

- id: lock_auto_lock_door_switch_update_locked
  alias: 'Lock Auto Lock Door Switch Update Locked'
  trigger:
    platform: state
    entity_id: lock.schlage_deadbolt_91
    to: 'locked'
    from: 'unlocked'
  condition:
    - condition: state
      entity_id: input_boolean.autolock
      state: 'off'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.lock_auto_lock_door_on

- id: lock_minimote_button_1_pressed
  alias: 'Lock Minimote button 1 Pressed'
  trigger:
    platform: state
    entity_id: sensor.minimote_72
    to: '1'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: lock.unlock
      entity_id: lock.schlage_deadbolt_91

- id: lock_minimote_button_3_pressed
  alias: 'Lock Minimote button 3 Pressed'
  trigger:
    platform: state
    entity_id: sensor.minimote_72
    to: '3'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.lock_auto_lock_door_off

- id: lock_door_opened_update_input_boolean
  alias: 'Lock Door Opened Update Input Boolean'
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_sensor_73
  condition:
    - condition: state
      entity_id: input_boolean.door_open
      state: 'off'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.door_open

- id: lock_door_opened_poll_lock
  alias: 'Lock Door Opened Poll Lock'
  trigger:
    platform: state
    entity_id: input_boolean.door_open
    to: 'on'
    for:
      seconds: 60
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.poll_front_door_when_opened
    - delay: 00:00:30
    - service: script.lock_update_door_open_boolean
