# Parents
- id: lock_parents_lock_code_toggle
  alias: 'Lock Parents Lock Code Toggle'
  trigger:
    - platform: state
      entity_id: input_boolean.parents_lock_code
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service_template: >
          {% if is_state('input_boolean.parents_lock_code', 'on') %}
            script.lock_set_parents_lock_code
          {% else %}
            script.lock_clear_parents_lock_code
          {% endif %}

# Temporary Lock Code
- id: lock_set_temp_lock_code
  alias: 'Lock Set Temporary Lock Code'
  trigger:
    - platform: state
      entity_id: input_text.lock_code_temp
  condition:
    - condition: template
      value_template: "{{ not is_state('input_text.lock_code_temp', 'Code') }}"
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.lock_set_temp_lock_code

- id: lock_clear_temp_lock_code
  alias: 'Lock Clear Temp Lock Code'
  trigger:
    - platform: state
      entity_id: input_boolean.temp_lock_code_set
      to: 'off'
      from: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.lock_clear_temp_code