- id: presence_automations_on
  alias: 'Presence Automations On'
  trigger:
    platform: state
    entity_id: input_boolean.presence_automations
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service_template: >
          {% if is_state('binary_sensor.anyone_home', 'on') and now().hour >= 6 and now().hour < 11 %}
            script.thermostat_home_set_temp
          {% else %}
            script.thermostat_temp_everyone_away
          {% endif %}

- id: presence_leave
  alias: 'Presence Leave'
  trigger:
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
  action:
    - service: script.presence_no_humans_home

- id: presence_update_butters_input_boolean
  alias: 'Presence Update Butters Input Boolean'
  trigger:
    - platform: state
      entity_id: device_tracker.butters
      to: 'home'
      from: 'not_home'
    - platform: state
      entity_id: device_tracker.butters
      to: 'not_home'
      from: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service_template: >
          {% if is_state('device_tracker.butters', 'home') %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
      data:
        entity_id: input_boolean.butters_home

- id: presence_butters_not_home
  alias: 'Presence Butters Not Home'
  trigger:
    - platform: state
      entity_id: input_boolean.butters_home
      to: 'off'
    - platform: state
      entity_id: device_tracker.neil
      to: 'not_home'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'off'
  action:
    - service: script.presence_no_humans_home

- id: presence_someone_home
  alias: 'Presence Someone Home'
  trigger:
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.away
      state: 'on'
  action:
    - service: script.presence_someone_arrived

- id: presence_turn_desktop_display_off
  alias: 'Presence Turn Desktop Display Off'
  trigger: 
    - platform: state
      entity_id: device_tracker.neil
      to: 'not_home'
      for:
        hours: 1
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: shell_command.desktop_screen_off

- id: presence_from_tasker_when_near_home
  alias: 'Presence From Tasker When Near Home'
  trigger:
    - platform: time_pattern
      minutes: '/30'
  condition:
    - condition: numeric_state
      entity_id: proximity.neil_home
      below: 30
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.presence_tasker_phone_location

- id: presence_from_tasker_when_far_from_home
  alias: 'Presence From Tasker When Far From Home'
  trigger:
    - platform: time_pattern
      hours: '/6'
  condition:
    - condition: numeric_state
      entity_id: proximity.neil_home
      above: 30
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.presence_tasker_phone_location