- id: presence_automations_on
  alias: 'Presence Automations On'
  trigger:
    platform: state
    entity_id: input_boolean.presence_automations
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service_template: >
          {% if is_state('binary_sensor.anyone_home', 'on') %}
            script.thermostat_home_set_temp
          {% else %}
            script.thermostat_temp_everyone_away
          {% endif %}

- id: presence_leave
  alias: 'Presence Leave'
  trigger:
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
  action:
    - service: script.presence_no_humans_home

- id: presence_update_butters_input_boolean
  alias: 'Presence Update Butters Input Boolean'
  trigger:
    - platform: state
      entity_id: person.butters
      to: 'home'
      from: 'not_home'
    - platform: state
      entity_id: person.butters
      to: 'not_home'
      from: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service_template: >
          {% if is_state('person.butters', 'home') %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
      data:
        entity_id: input_boolean.butters_home

- id: presence_butters_not_home
  alias: 'Presence Butters Not Home'
  trigger:
    - platform: state
      entity_id: input_boolean.butters_home
      to: 'off'
    - platform: state
      entity_id: person.neil
      to: 'not_home'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.away
      state: 'on'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'off'
  action:
    - service: script.presence_no_humans_home

- id: presence_someone_home
  alias: 'Presence Someone Home'
  trigger:
    - platform: state
      entity_id: person.neil
      to: 'home'
    - platform: state
      entity_id: person.parents
      to: 'home'
    - platform: state
      entity_id: person.gina
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.away
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
  action:
    - service: script.presence_someone_arrived

- id: presence_motion_sensor_tripped
  alias: 'Presence Motion Sensor Tripped'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_108
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.motion_detected

- id: presence_motion_sensor_turn_off_boolean
  alias: 'Presence Motion Sensor Turn Off Boolean'
  trigger:
    - platform: state
      entity_id: input_boolean.motion_detected
      to: 'on'
      for: "00:05:00"
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.motion_detected

- id: presence_motion_sensor_tripped_lights_on
  alias: 'Presence Motion Sensor Lights On'
  trigger:
    - platform: state
      entity_id: input_boolean.motion_detected
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: light.kitchen
      state: 'off'
    - condition: state
      entity_id: binary_sensor.dark_out
      state: 'on'
  action:
    - service: script.presence_arrive_dark_out


- id: presence_motion_sensor_lights_off
  alias: 'Presence Motion Sensor Lights Off'
  trigger:
    - platform: state
      entity_id: input_boolean.motion_detected
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'off'
    - condition: state
      entity_id: light.kitchen
      state: 'on'
  action:
    - service: script.kitchen_lights_off

- id: lock_code_used_not_family
  alias: 'Lock Code Used Not Family'
  trigger:
    - platform: state
      entity_id: sensor.last_lock_code_name
      to: 'Temp'
    - platform: state
      entity_id: sensor.last_lock_code_name
      to: 'Guest'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: binary_sensor.lock_code_entered
      state: 'on'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'off'
    - condition: state
      entity_id: binary_sensor.lock_code_entered_neil
      state: 'off'
    - condition: state
      entity_id: binary_sensor.lock_code_entered_gina
      state: 'off'
    - condition: state
      entity_id: binary_sensor.lock_code_entered_parents
      state: 'off'
  action:
    - service: script.presence_lock_code_entered_not_family

- id: presence_turn_desktop_display_off
  alias: 'Presence Turn Desktop Display Off'
  trigger: 
    - platform: state
      entity_id: person.neil
      to: 'not_home'
      for:
        hours: 1
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.system_desktop_display_off
    - service: rest_command.mirror_hide_all_modules
