- id: presence_automations_on
  alias: 'Presence Automations On'
  trigger:
    platform: state
    entity_id: input_boolean.presence_automations
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service_template: >
          {% if is_state('binary_sensor.anyone_home', 'on') %}
            script.thermostat_home_set_temp
          {% else %}
            script.thermostat_temp_everyone_away
          {% endif %}

- id: presence_leave
  alias: 'Presence Leave'
  trigger:
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
  action:
    - service: script.presence_no_humans_home

- id: presence_update_butters_input_boolean
  alias: 'Presence Update Butters Input Boolean'
  trigger:
    - platform: state
      entity_id: device_tracker.butters
      to: 'home'
      from: 'not_home'
    - platform: state
      entity_id: device_tracker.butters
      to: 'not_home'
      from: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service_template: >
          {% if is_state('device_tracker.butters', 'home') %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
      data:
        entity_id: input_boolean.butters_home

- id: presence_butters_not_home
  alias: 'Presence Butters Not Home'
  trigger:
    - platform: state
      entity_id: input_boolean.butters_home
      to: 'off'
    - platform: state
      entity_id: device_tracker.neil
      to: 'not_home'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.away
      state: 'on'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'off'
  action:
    - service: script.presence_no_humans_home

- id: presence_someone_home
  alias: 'Presence Someone Home'
  trigger:
    - platform: state
      entity_id: device_tracker.neil
      to: 'home'
    - platform: state
      entity_id: device_tracker.parents
      to: 'home'
    - platform: state
      entity_id: device_tracker.gina
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.away
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
  action:
    - service: script.presence_someone_arrived

- id: lock_temp_lock_code_used
  alias: 'Lock Temp Lock Code Used'
  trigger:
    - platform: state
      entity_id: sensor.last_lock_code_name
      to: 'Temp'
    - platform: state
      entity_id: sensor.last_lock_code_name
      to: 'Guest'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: binary_sensor.lock_code_entered
      state: 'on'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'off'
  action:
    - service: script.presence_lock_code_entered_not_family

- id: presence_turn_desktop_display_off
  alias: 'Presence Turn Desktop Display Off'
  trigger: 
    - platform: state
      entity_id: device_tracker.neil
      to: 'not_home'
      for:
        hours: 1
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: shell_command.desktop_screen_off