- id: presence_automations_on
  alias: 'Presence Automations On'
  initial_state: false
  trigger:
    platform: state
    entity_id: input_boolean.presence_automations
    to: 'on'
  action:
    - service_template: >
          {% if is_state('binary_sensor.anyone_home', 'on') and now().hour >= 6 and now().hour < 11 %}
            script.thermostat_home_set_temp
          {% else %}
            script.thermostat_temp_everyone_away
          {% endif %}

- id: presence_leave
  alias: 'Presence Leave'
  initial_state: false
  trigger:
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
  action:
    - service: script.presence_leave

- id: presence_update_butters_input_boolean
  alias: 'Presence Update Butters Input Boolean'
  initial_state: false
  trigger:
    - platform: state
      entity_id: device_tracker.butters
      to: 'home'
      from: 'not_home'
    - platform: state
      entity_id: device_tracker.butters
      to: 'not_home'
      from: 'home'
  action:
    - service_template: > 
          {% if is_state('device_tracker.butters', 'home') %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
      data:
        entity_id: input_boolean.butters_home

- id: presence_butters_not_home
  alias: 'Presence Butters Not Home'
  initial_state: false
  trigger:
    - platform: state
      entity_id: input_boolean.butters_home
      to: 'off'
    - platform: state
      entity_id: device_tracker.neil
      to: 'not_home'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'off'
  action:
    - service: script.presence_leave

- id: presence_neil_home
  alias: 'Presence Neil Home'
  initial_state: false
  trigger:
    - platform: state
      entity_id: device_tracker.neil
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.away
      state: 'on'
  action:
    - service: script.presence_arrive
    - delay:
        seconds: 5
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.kitchen_home
        volume_level: 0.6
    - service: tts.google_say
      entity_id: media_player.kitchen_home
      data:
        message: "Hello, Neil"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.parents_lock_code

- id: presence_family_home
  alias: 'Presence Family Home'
  initial_state: false
  trigger:
    - platform: state
      entity_id: binary_sensor.anyone_home_but_neil
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.away
      state: 'on'
  action:
    - service_template: >
          {% if is_state('device_tracker.parents', 'home') %}
            script.presence_parents_home
          {% else %}
            script.presence_gina_home
          {% endif %}

- id: presence_turn_desktop_display_off
  alias: 'Presence Turn Desktop Display Off'
  initial_state: false
  trigger: 
    - platform: state
      entity_id: device_tracker.neil
      to: 'not_home'
      for:
        hours: 1
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: shell_command.desktop_screen_off

- id: presence_from_tasker_when_near_home
  alias: 'Presence From Tasker When Near Home'
  initial_state: false
  trigger:
    - platform: time
      minutes: 30
  condition:
    - condition: numeric_state
      entity_id: proximity.neil_home
      below: 30
  action:
    - service: script.presence_tasker_phone_location

- id: presence_from_tasker_when_far_from_home
  alias: 'Presence From Tasker When Far From Home'
  initial_state: false
  trigger:
    - platform: time
      hours: 6
  condition:
    - condition: numeric_state
      entity_id: proximity.neil_home
      above: 30
  action:
    - service: script.presence_tasker_phone_location