- id: system_startup
  alias: 'System Startup'
  hide_entity: true
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: logbook.log
      data_template:
        name: Starting
        message: Hass is Starting
    - service: scene.turn_on
      entity_id: scene.startup_reset_variables
    - delay: 00:00:05
    - service: shell_command.restart_pi_sys_stat
    - delay: 00:00:50
    - service: script.startup_scripts
    - delay: 00:01:00
    - service_template: >
          {% if (((as_timestamp(now()) - as_timestamp(states.sensor.last_boot.state)) )| int) < 360 %}
            script.system_restart_if_just_rebooted
          {% else %}
            script.system_turn_on_automations_on_restart
          {% endif %}
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.restart_complete

- id: system_internet_down
  alias: 'System Internet Down'
  trigger: 
    - platform: template
      value_template: '{{ states.sensor.speedtest_download.state| float < 5 }}'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:      
    - service: script.restart_homeassistant
    
- id: system_monitor_pi_zero_down
  alias: 'System Monitor Pi Zero Down'
  trigger: 
    - platform: state
      entity_id: sensor.neil_mqtt_pixel
      to: 'unknown'
      for:
        minutes: 5
    - platform: state
      entity_id: sensor.neil_mqtt_charge_2
      to: 'unknown'
      for:
        minutes: 5
    - platform: state
      entity_id: sensor.butters_mqtt_tile
      to: 'unknown'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: shell_command.restart_monitor

- id: system_scheduled_reboot_pi
  alias: 'System Scheduled Reboot Pi'
  trigger:
    platform: time
    at: '04:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: time
      weekday:
      - mon
  action:
    - service: shell_command.reboot_pi_zero
    - delay: 00:10:00
    - service: script.system_reboot

- id: system_scheduled_restart_ha
  alias: 'System Scheduled Restart HA'
  trigger:
    platform: time
    at: '04:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: time
      weekday:
      - mon
      - wed
      - fri
  action:
    - service: script.restart_homeassistant

- id: system_update_input_boolean_for_config_backup
  alias: 'System Update Input Boolean for Config Backup'
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: created
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: deleted
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: moved
  condition:
    - condition: state
      entity_id: input_boolean.config_updated
      state: 'off'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.config_updated

- id: system_backup_config
  alias: 'System Backup Config'
  trigger:
    platform: time
    at: '03:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.config_updated
      state: 'on'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: shell_command.git_backup
    - delay: 00:00:60
    - service: hassio.snapshot_full
      data_template:
        name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.config_updated
    - delay: 00:10:00
    - service: shell_command.desktop_backup_sync
    - delay: 00:00:10
    - condition: time
      weekday:
      - sun
      - tue
      - thu
      - sat
    - service: script.restart_homeassistant

- id: system_reboot_confirmed
  alias: 'System Reboot Confirmed'
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: confirm_system_reboot
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.system_reboot