- id: system_startup
  alias: 'System Startup'
  hide_entity: true
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: logbook.log
      data_template:
        name: Starting
        message: Hass is Starting
    - service: scene.turn_on
      entity_id: scene.startup_reset_variables
    - delay: 00:00:50
    - service: script.startup_scripts
    

- id: system_scheduled_reboot_pi
  alias: 'System Scheduled Reboot Pi'
  trigger:
    platform: time
    at: '03:40:00'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: time
      weekday:
      - mon
  action:
    - service_template: >
          {% if is_state('input_boolean.config_updated', 'on') %}
            script.system_backup
          {% else %}
            script.do_nothing
          {% endif %}
    - delay: 00:20:00
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.config_updated
    - service: script.system_reboot

# - id: system_scheduled_restart_ha
  # alias: 'System Scheduled Restart HA'
  # trigger:
    # platform: time
    # at: '04:00:00'
  # condition:
    # - condition: state
      # entity_id: input_boolean.config_updated
      # state: 'off'
    # - condition: state
      # entity_id: input_boolean.restart_complete
      # state: 'on'
    # - condition: time
      # weekday:
      # - wed
      # - fri
  # action:
    # - service: script.restart_homeassistant

- id: system_update_input_boolean_for_config_backup
  alias: 'System Update Input Boolean for Config Backup'
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: created
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: deleted
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: moved
  condition:
    - condition: state
      entity_id: input_boolean.config_updated
      state: 'off'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.config_updated

- id: system_backup_config
  alias: 'System Backup Config'
  trigger:
    platform: time
    at: '03:40:00'
  condition:
    - condition: state
      entity_id: input_boolean.config_updated
      state: 'on'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.system_backup
    - condition: time
      weekday:
      - sun
      - tue
      - wed
      - thu
      - fri
      - sat
    - delay: 00:20:00
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.config_updated
    - service: script.restart_homeassistant

- id: system_reboot_confirmed
  alias: 'System Reboot Confirmed'
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: confirm_system_reboot
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.system_reboot

- id: system_reload_lovelace
  alias: 'System Reload Lovelace'
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: created
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: deleted
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: moved
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: browser_mod.lovelace_reload