- id: system_startup
  alias: 'System Startup'
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: script.system_run_startup_shell_commands_on_boot
    - service: frontend.set_theme
      data:
        name: clear-dark2
    - delay: 00:00:20
    - service: script.startup_scripts

- id: system_update_input_boolean_for_config_backup
  alias: 'System Update Input Boolean for Config Backup'
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: created
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: deleted
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: moved
  condition:
    - condition: state
      entity_id: input_boolean.config_updated
      state: 'off'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.config_updated

- id: system_backup_config
  alias: 'System Backup Config'
  trigger:
    platform: time
    at: '03:40:00'
  condition:
    - condition: state
      entity_id: input_boolean.config_updated
      state: 'on'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.system_git_backup
    - condition: time
      weekday:
      - sun
      - tue
      - wed
      - thu
      - fri
      - sat
    - delay: 00:20:00
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.config_updated
    - service: script.restart_homeassistant

- id: system_reboot_confirmed
  alias: 'System Reboot Confirmed'
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: confirm_system_reboot
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.system_reboot

- id: system_turn_pi_hole_back_on
  alias: 'Turn Pihole On'
  trigger:
    platform: state
    entity_id: switch.pi_hole
    to: 'off'
    for:
      minutes: 5
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.pi_hole
- id: system_ping_healthchecks
  alias: 'System Ping Healthchecks'
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: shell_command.healthchecks_ping
