# Set Temp on Weather Minus Morning
- id: thermostat_set_temp_when_home_after_11_am
  alias: 'Thermostat Set Temp When Home after 11 AM'
  trigger:
    - platform: state
      entity_id: sensor.temp
    - platform: time
      at: '11:01:00'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'on'
    - condition: time
      after: '11:00:00'
      before: '06:00:00'
  action:
    - service: script.thermostat_set_home_not_morning
      
# Set Temp on Weather In Morning
- id: thermostat_set_temp_when_home_after_6_am
  alias: 'Thermostat Set Temp When Home after 6 AM'
  trigger:
    - platform: state
      entity_id: sensor.temp
    - platform: time
      at: '06:01:00'
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'on'
    - condition: time
      after: '06:00:00'
      before: '11:00:00'
  action:
    - service: script.thermostat_set_home_morning

- id: thermostat_set_when_away
  alias: 'Thermostat Set When Away'
  trigger:
    - platform: state
      entity_id: sensor.temp
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: binary_sensor.anyone_home
      state: 'off'
  action:
    - service_template: >
          {% if is_state('input_boolean.butters_home', 'off') %}
            script.thermostat_temp_everyone_away
          {% else %}
            script.thermostat_set_temp_only_butters_home
          {% endif %}