- id: tv_open_casting_apps
  alias: 'TV Open Casting Apps'
  initial_state: false
  trigger:
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube TV') %} true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube') %} true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'Plex') %} true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'HBO GO') %} true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'Showtime Anytime') %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube Music') %} true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'Netflix') %} true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'Starz') %} true{% endif %}"
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: joaoapps_join.pixel_send_tasker
      data_template:
        command: >
          {% if is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube TV') %}
            yttv
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Netflix') %}
            netflix
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube Music') %}
            ytmusic
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube') %}
            yt
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Plex') %}
            plex
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'HBO GO') %}
            hbo
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Starz') %}
            starz
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Showtime Anytime') %}
            showtime
          {% else %}
          {% endif %}
    - service: joaoapps_join.fire_send_tasker
      data:
        command: max_brightness
    - service: joaoapps_join.fire_send_tasker
      data_template:
        command: >
          {% if is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube TV') %}
            yttv
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Netflix') %}
            netflix
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube Music') %}
            ytmusic
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube') %}
            yt
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Plex') %}
            plex
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'HBO GO') %}
            hbo
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Starz') %}
            starz
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Showtime Anytime') %}
            showtime
          {% else %}
          {% endif %}


- id: tv_on_notify_theater_mode
  alias: 'TV On Notify Theater Mode'
  initial_state: false
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      from: 'off'
      to: 'playing'
      for:
        seconds: 60
  condition:
    - condition: state
      entity_id: input_boolean.notifications_on
      state: 'on'
    - condition: state
      entity_id: device_tracker.neil
      state: 'home'
  action:
    - service: notify.html5
      data:
        message: "Turn on Theater Mode?"
        data: {
          renotify: 0,
          tag: 'tv',
          icon: '/local/tv.jpg',
          badge: '/local/television.png',
          actions: [
            {
              action: "theater_mode",
              title: "Theater Mode"
            },
            {
              action: "dismiss",
              title: "Dismiss"
            },
      ]
    }
- id: tv_on_notify_theater_mode_selected
  alias: 'TV On Notify Theater Mode Selected'
  initial_state: false
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: theater_mode
  action:
    service: homeassistant.turn_on
    entity_id: scene.theater_mode

- id: tv_input_boolean_control
  alias: 'TV Input Boolean Control'
  initial_state: false
  trigger:
    - platform: state
      entity_id: input_boolean.tv_power
  action:
    - service_template: >
          {% if is_state('input_boolean.tv_power', 'on') %}
            script.tv_on
          {% else %}
            script.tv_off
          {% endif %}

- id: tv_update_input_boolean_from_sensor
  alias: 'TV Update Input Boolean from Sensor'
  initial_state: false
  trigger:
    - platform: state
      entity_id: sensor.tv_mqtt_monitor
      to: 'ON'
      from: 'OFF'
      for:
        seconds: 120
    - platform: state
      entity_id: sensor.tv_mqtt_monitor
      to: 'OFF'
      from: 'ON'
      for:
        seconds: 120
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: template
      value_template: "{{ (as_timestamp(now()) - as_timestamp(states.input_boolean.tv_power.last_updated)) | int > 60 }}"
  action:
    - service_template: >
          {% if is_state('sensor.tv_mqtt_monitor', 'ON') %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
      data:
        entity_id: input_boolean.tv_power

- id: tv_restart_mqtt_monitor
  alias: 'TV Restart MQTT Monitor'
  initial_state: false
  trigger:
    - platform: template
      value_template: "{% if (as_timestamp(now()) - as_timestamp(states.sensor.tv_mqtt_monitor.last_updated)) > 600 %} true {% endif %}"
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: shell_command.restart_tv_status_monitor