- id: tv_open_casting_apps
  alias: 'TV Open Casting Apps'
  trigger:
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube TV') %} true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube') %} true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'Plex') %} true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'HBO GO') %} true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'Showtime Anytime') %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube Music') %} true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'Netflix') %} true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room_tv', 'app_name', 'Starz') %} true{% endif %}"
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: joaoapps_join.pixel_send_tasker
      data_template:
        command: >
          {% if is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube TV') %}
            yttv
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Netflix') %}
            netflix
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube Music') %}
            ytmusic
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube') %}
            yt
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Plex') %}
            plex
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'HBO GO') %}
            hbo
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Starz') %}
            starz
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Showtime Anytime') %}
            showtime
          {% else %}
          {% endif %}
    - service: joaoapps_join.fire_send_tasker
      data:
        command: max_brightness
    - service: joaoapps_join.fire_send_tasker
      data_template:
        command: >
          {% if is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube TV') %}
            yttv
          # {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Netflix') %}
            # netflix
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube Music') %}
            ytmusic
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'YouTube') %}
            yt
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Plex') %}
            plex
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'HBO GO') %}
            hbo
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Starz') %}
            starz
          {%-elif is_state_attr('media_player.living_room_tv', 'app_name', 'Showtime Anytime') %}
            showtime
          {% else %}
          {% endif %}

- id: tv_on_notify_theater_mode
  alias: 'TV On Notify Theater Mode'
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      from: 'off'
      to: 'playing'
      for:
        seconds: 60
    - platform: state
      entity_id: switch.hdmi_0
      to: 'on'
      from: 'off'
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: input_boolean.notifications_on
      state: 'on'
    - condition: state
      entity_id: device_tracker.neil
      state: 'home'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.tv_notify_theater_mode

- id: tv_on_notify_theater_mode_selected
  alias: 'TV On Notify Theater Mode Selected'
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: theater_mode
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: script.tv_turn_on_theater_mode

- id: tv_off_turn_devices_off
  alias: 'TV Off Turn Devices Off'
  trigger:
    - platform: state
      entity_id: switch.hdmi_0
      to: 'off'
      from: 'on'
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence_running
      state: 'off'
  action:
    - service: script.tv_off_turn_devices_off