- id: weather_notify_precipitation
  alias: 'Weather Notify Precipitation'
  trigger:
    - platform: state
      entity_id: sensor.precipitation_soon
      to: 'Rain'
    - platform: state
      entity_id: sensor.precipitation_soon
      to: 'Sleet'
    - platform: state
      entity_id: sensor.precipitation_soon
      to: 'Snow'
  condition:
    - condition: state
      entity_id: input_boolean.notifications_on
      state: 'on'
    - condition: state
      entity_id: input_boolean.weather_notifications
      state: 'on'
    - condition: state
      entity_id: input_boolean.weather_dont_renotify
      state: 'off'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service_template: >
          {% if is_state('sensor.precipitation_soon', 'Rain') %}
            script.notify_rain
          {%-elif is_state('sensor.precipitation_soon', 'Snow') %}
            script.notify_snow
          {% else %}
            script.notify_sleet
          {% endif %}
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.weather_dont_renotify

- id: weather_allow_renotify_after_1_hour
  alias: 'Weather Allow Renotify After 1 Hour'
  trigger:
    - platform: state
      entity_id: input_boolean.weather_dont_renotify
      to: 'on'
      for:
        hours: 1
  condition:
    - condition: state
      entity_id: input_boolean.notifications_on
      state: 'on'
    - condition: state
      entity_id: input_boolean.weather_notifications
      state: 'on'
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.weather_dont_renotify

- id: weather_notifications_off
  alias: 'Weather Notifications Off'
  trigger:
    - platform: state
      entity_id: device_tracker.neil
      to: 'not_home'
      for:
        hours: 6
  condition:
    - condition: state
      entity_id: input_boolean.restart_complete
      state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.weather_dont_renotify